# Switch now and for all next steps to your control plane
# Get credentials from someone or create them
# https://sap.github.io/crossplane-provider-docs/docs/crossplane-provider-btp/docs/end-user-guides/setup/configure-provider-btp 
---
apiVersion: v1
data:
  data: ...
kind: Secret
metadata:
  name: cis-provider-secret
  namespace: default
type: Opaque

---

apiVersion: v1
data:
  credentials: ...
kind: Secret
metadata:
  name: sa-provider-secret
  namespace: default
type: Opaque
